version: "3"

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis_cache:/data:rw
  rollup-sync:
    build: .
    depends_on:
      - redis
    ports:
      - 8545:8545
      - 8546:8546

volumes:
  redis_cache:
