version: "3"

services:
  redis:
    image: redis:6-alpine
    volumes:
      - redis_cache:/data:rw
  rollup-sync:
    build: .
    depends_on:
      - redis
    ports:
      - 8545:8545
      - 8546:8546
    environment:
      MAINNET_URL: ws://192.168.1.199:8546
      KOVAN_URL: ws://192.168.1.199:8850
      GOERLI_URL: ws://192.168.1.199:9546
      NETWORK_OVERRIDE: mainnet

volumes:
  redis_cache:
